//! Migration: create messages_fts FTS5 virtual table and triggers.

use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Create FTS5 virtual table for messages content.
        // We store the message content and reference the original message id.
        // The rowid is auto-generated by FTS5 – we do not insert into it.
        let sql = r#"
            CREATE VIRTUAL TABLE IF NOT EXISTS messages_fts USING fts5(content, message_id UNINDEXED);

            -- Drop existing triggers to make migration idempotent.
            DROP TRIGGER IF EXISTS messages_ai;
            DROP TRIGGER IF EXISTS messages_au;
            DROP TRIGGER IF EXISTS messages_ad;

            -- Trigger after insert on messages
            CREATE TRIGGER messages_ai AFTER INSERT ON messages BEGIN
                INSERT INTO messages_fts(content, message_id) VALUES (new.content, new.id);
            END;

            -- Trigger after update on messages (if content changes)
            CREATE TRIGGER messages_au AFTER UPDATE OF content ON messages BEGIN
                UPDATE messages_fts SET content = new.content WHERE message_id = old.id;
            END;

            -- Trigger after delete on messages
            CREATE TRIGGER messages_ad AFTER DELETE ON messages BEGIN
                DELETE FROM messages_fts WHERE message_id = old.id;
            END;

            -- Initial population (idempotent via INSERT OR IGNORE)
            INSERT OR IGNORE INTO messages_fts(content, message_id) SELECT content, id FROM messages;
        "#;

        manager.get_connection().execute_unprepared(sql).await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let sql = r#"
            DROP TABLE IF EXISTS messages_fts;
            DROP TRIGGER IF EXISTS messages_ai;
            DROP TRIGGER IF EXISTS messages_au;
            DROP TRIGGER IF EXISTS messages_ad;
        "#;
        manager.get_connection().execute_unprepared(sql).await?;
        Ok(())
    }
}
