
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async unlockAchievement(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unlock_achievement", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAchievements() : Promise<Result<AchievementData[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_achievements") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async compactConversation(conversationId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compact_conversation", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkProviderReady(profileId: string) : Promise<Result<ProviderReadyInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_provider_ready", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getArtifactContent(artifactId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_artifact_content", { artifactId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listBuiltInThemes() : Promise<Result<ThemeInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_built_in_themes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSyntaxCss() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_syntax_css") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setBuiltInTheme(themeName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_built_in_theme", { themeName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setThemeFromFile(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_theme_from_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get conversation bootstrap data (messages, branches, draft, queued, headings).
 */
async getConversationBootstrap(conversationId: string) : Promise<Result<ConversationBootstrapData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conversation_bootstrap", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pinArtifact(artifactId: string, branchId: string | null, isGlobal: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pin_artifact", { artifactId, branchId, isGlobal }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unpinArtifact(artifactId: string, branchId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unpin_artifact", { artifactId, branchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPinnedArtifacts(conversationId: string, branchId: string | null) : Promise<Result<ArtifactData[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_pinned_artifacts", { conversationId, branchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listArtifactVersions(artifactId: string) : Promise<Result<ArtifactData[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_artifact_versions", { artifactId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async copyArtifactToBranch(artifactId: string, targetBranchId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_artifact_to_branch", { artifactId, targetBranchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listArtifacts(conversationId: string, branchId: string | null) : Promise<Result<ArtifactData[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_artifacts", { conversationId, branchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHomeDir() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_home_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConversationDraft(conversationId: string) : Promise<Result<[string, JsonValue[]] | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conversation_draft", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async upsertConversationDraft(conversationId: string, textContent: string | null, contextItems: JsonValue[] | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upsert_conversation_draft", { conversationId, textContent, contextItems }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async attachFilesToConversation(conversationId: string, paths: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("attach_files_to_conversation", { conversationId, paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listFolders() : Promise<Result<FolderData[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_folders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFolder(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameFolder(id: string, name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_folder", { id, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteFolder(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_folder", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveConversationToFolder(conversationId: string, folderId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_conversation_to_folder", { conversationId, folderId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the global auto-approve configuration.
 */
async setAutoApproveConfig(config: AutoApproveConfigDto) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_auto_approve_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addBookmark(req: CreateBookmarkRequest) : Promise<Result<BookmarkData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_bookmark", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeBookmark(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_bookmark", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listBookmarks(conversationId: string) : Promise<Result<BookmarkData[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_bookmarks", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleBookmark(conversationId: string, messageId: string, headingAnchor: string | null, label: string | null) : Promise<Result<BookmarkData | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_bookmark", { conversationId, messageId, headingAnchor, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAnalytics() : Promise<Result<AnalyticsData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_analytics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async processQueuedMessages(conversationId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("process_queued_messages", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAutoSendPaused(conversationId: string, paused: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_auto_send_paused", { conversationId, paused }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new branch from a parent message.
 */
async createBranch(req: CreateBranchRequest) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_branch", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all branches for a conversation.
 */
async listBranches(conversationId: string) : Promise<Result<BranchInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_branches", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get messages for a specific branch.
 */
async getBranchMessages(branchId: string) : Promise<Result<MessageData[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_branch_messages", { branchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a new workflow definition.
 */
async saveWorkflowDefinition(req: SaveWorkflowDefinitionRequest) : Promise<Result<WorkflowDefinitionResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_workflow_definition", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all workflow definitions.
 */
async listWorkflowDefinitions() : Promise<Result<WorkflowDefinitionResponse[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workflow_definitions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a single workflow definition by ID.
 */
async getWorkflowDefinition(id: string) : Promise<Result<WorkflowDefinitionResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_workflow_definition", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a workflow definition.
 */
async deleteWorkflowDefinition(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_workflow_definition", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update an existing workflow definition.
 */
async updateWorkflowDefinition(id: string, name: string, definition: JsonValue) : Promise<Result<WorkflowDefinitionResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_workflow_definition", { id, name, definition }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run a workflow definition and emit events.
 */
async runWorkflowDefinition(id: string, providerId: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_workflow_definition", { id, providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInstalledSkillContent(skillName: string, target: InstallTarget) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_installed_skill_content", { skillName, target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInstalledSkillPath(skillName: string, target: InstallTarget) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_installed_skill_path", { skillName, target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Install a skill from the registry by ID.
 */
async installRegistrySkill(skillId: string, target: InstallTarget, overwrite: boolean | null) : Promise<Result<InstallResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_registry_skill", { skillId, target, overwrite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a folder in the system file explorer.
 */
async openFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Synchronize skills from the platform registry (Tauri command).
 */
async syncRegistrySkills() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_registry_skills") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch registry skills from the local cache.
 */
async fetchRegistrySkills(category: string | null, search: string | null) : Promise<Result<RegistrySkillData[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_registry_skills", { category, search }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new conversation for the given profile.
 */
async createConversation(profileId: string, title: string | null, workspaceId: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_conversation", { profileId, title, workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return conversations for a profile (or all profiles if profile_id is null), most-recently-updated first.
 */
async listConversations(profileId: string | null, limit: string | null) : Promise<Result<ConversationSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_conversations", { profileId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Soft-delete a conversation.
 */
async deleteConversation(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_conversation", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a conversation.
 */
async renameConversation(id: string, title: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_conversation", { id, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMessages(conversationId: string, branchId: string | null) : Promise<Result<MessageData[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_messages", { conversationId, branchId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search messages within a conversation using FTS5.
 */
async searchMessages(req: SearchMessagesRequest) : Promise<Result<SearchMessagesResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_messages", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Mark a single message as seen.
 */
async markMessageSeen(messageId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_message_seen", { messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendMessage(req: SendMessageRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_message", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveToolApproval(toolCallId: string, approved: boolean, editedInput: JsonValue | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_tool_approval", { toolCallId, approved, editedInput }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all profiles ordered by default-first, then alphabetically.
 */
async listProfiles(includeDeleted: boolean | null) : Promise<Result<ProfileData[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_profiles", { includeDeleted }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new profile, optionally with a system prompt.
 */
async createProfile(name: string, modelProvider: string, modelId: string, systemPrompt: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_profile", { name, modelProvider, modelId, systemPrompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Partial update — only provided fields are mutated.
 */
async updateProfile(id: string, name: string | null, modelProvider: string | null, modelId: string | null, systemPrompt: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_profile", { id, name, modelProvider, modelId, systemPrompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Soft delete a profile. Refuses to delete the last remaining active profile.
 */
async deleteProfile(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_profile", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set a profile as the default, clearing the flag on all others.
 */
async setDefaultProfile(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_default_profile", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Restore a soft-deleted profile. Ensures the profile is not marked as default.
 */
async restoreProfile(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_profile", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return key-presence status for every known provider.
 */
async listApiKeys() : Promise<Result<ApiKeyStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_api_keys") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Store (or replace) an API key in the OS keychain and refresh the provider
 * registry so the agent loop can use the new key immediately.
 */
async setApiKey(provider: string, key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_api_key", { provider, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove an API key from the OS keychain.
 * Tolerates missing entries (idempotent).
 */
async deleteApiKey(provider: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_api_key", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Light format-based validation – does not make a real API call.
 * 
 * Use this for immediate feedback in the settings UI; real connectivity
 * is verified the first time the agent loop attempts a completion.
 */
async validateApiKey(provider: string, key: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_api_key", { provider, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSkills() : Promise<Result<SkillInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skills") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleSkill(name: string, active: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_skill", { name, active }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lint a single skill directory, merging workspace config if present.
 */
async lintSkill(path: string, workspaceConfigPath: string | null) : Promise<Result<LintWarning[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("lint_skill", { path, workspaceConfigPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lint all known local skill source directories.
 */
async lintAllLocalSources() : Promise<Result<Partial<{ [key in string]: LintWarning[] }>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("lint_all_local_sources") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all available lint rule IDs.
 */
async getLintRules() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_lint_rules") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Disable a lint rule by adding it to the TOML config file.
 */
async disableLintRule(ruleId: string, scope: ConfigScope) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disable_lint_rule", { ruleId, scope }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Install a skill into the personal or workspace location.
 */
async installSkill(skillName: string, skillContent: string, target: InstallTarget, overwrite: boolean | null) : Promise<Result<InstallResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_skill", { skillName, skillContent, target, overwrite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Uninstall a locally installed skill.
 */
async uninstallSkill(skillName: string, target: InstallTarget) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("uninstall_skill", { skillName, target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Compute a unified diff between the locally installed skill and a registry version.
 */
async diffSkillVersions(localPath: string, registryContent: string) : Promise<Result<DiffResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("diff_skill_versions", { localPath, registryContent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSkillSources() : Promise<Result<SkillSourceInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skill_sources") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addSkillSource(sourceType: string, path: string, label: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_skill_source", { sourceType, path, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeSkillSource(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_skill_source", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMcpServers() : Promise<Result<McpServerResponse[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_mcp_servers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async connectMcpServer(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_mcp_server", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async disconnectMcpServer(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disconnect_mcp_server", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addMcpServer(payload: AddMcpServerPayload) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_mcp_server", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeMcpServer(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_mcp_server", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export a conversation to a file on the local filesystem.
 */
async exportConversation(id: string, format: ExportFormat, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_conversation", { id, format, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Share a skill as a GitHub Gist.
 * 
 * `skill_name` — the skill's filesystem folder name.
 * `content_md` — the full SKILL.md content.
 */
async shareSkillAsGist(skillName: string, contentMd: string, description: string) : Promise<Result<GistInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("share_skill_as_gist", { skillName, contentMd, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Share a workflow definition as a GitHub Gist.
 */
async shareWorkflowAsGist(workflowName: string, workflowJson: JsonValue, description: string) : Promise<Result<GistInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("share_workflow_as_gist", { workflowName, workflowJson, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import a skill from a GitHub Gist URL or ID.
 * Returns the SKILL.md content so the frontend can write it to disk.
 */
async importSkillFromGist(gistId: string) : Promise<Result<GistFile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_skill_from_gist", { gistId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import a workflow from a Gist ID. Returns the parsed JSON value.
 */
async importWorkflowFromGist(gistId: string) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_workflow_from_gist", { gistId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export a conversation as Markdown with SkillDeck attribution footer.
 */
async exportConversationAsMarkdown(title: string, messages: MessageExport[], tags: string[]) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_conversation_as_markdown", { title, messages, tags }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check whether a GitHub token is already stored.
 */
async hasGithubToken() : Promise<boolean> {
    return await TAURI_INVOKE("has_github_token");
},
/**
 * Store a GitHub OAuth token in the keychain.
 */
async setGithubToken(token: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_github_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detect and open a workspace at the given path.
 * If the workspace already exists in the DB, it is reopened (updated) instead of inserted.
 */
async openWorkspace(path: string) : Promise<Result<WorkspaceData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_workspace", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Mark a workspace as closed.
 */
async closeWorkspace(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_workspace", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all workspaces (both open and closed)
 */
async listWorkspaces() : Promise<Result<WorkspaceData[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_workspaces") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listOllamaModels() : Promise<Result<OllamaModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_ollama_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ensurePlatformRegistration() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_platform_registration") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPlatformPreferences() : Promise<Result<PlatformPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_platform_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePlatformPreferences(payload: UpdatePreferencesRequest) : Promise<Result<PlatformPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_platform_preferences", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPendingNudges() : Promise<Result<PendingNudge[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_pending_nudges") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendActivityEvent(payload: ActivityEventRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_activity_event", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getReferralStats() : Promise<Result<ReferralStats, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_referral_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createReferralCode() : Promise<Result<ReferralCode, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_referral_code") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resendVerificationEmail() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resend_verification_email") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportGdprData() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_gdpr_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePlatformAccount() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_platform_account") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSharedConversation(shareToken: string) : Promise<Result<SharedConversationPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_shared_conversation", { shareToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkSyncStatus(conversationId: string) : Promise<Result<SyncStatusResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_sync_status", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async shareConversation(conversationId: string) : Promise<Result<ShareResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("share_conversation", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncConversationToPlatform(conversationId: string, payload: SyncConversationRequest) : Promise<Result<SyncConversationResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_conversation_to_platform", { conversationId, payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hydrateSharedConversation(payload: SharedConversationPayload) : Promise<Result<HydrateResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hydrate_shared_conversation", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelAgent(conversationId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_agent", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Test a provider API key by making a minimal API call.
 */
async testApiConnection(provider: string, key: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_api_connection", { provider, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the contents of a directory, including a `..` parent entry.
 * 
 * Hidden files, `node_modules`, and `target` are excluded.
 * I/O is offloaded to a blocking thread to avoid stalling the async runtime.
 */
async listDirectoryContents(path: string) : Promise<Result<FileEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_directory_contents", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Count files inside a folder at two depths: direct children only (shallow)
 * and all nested files recursively (deep).
 * 
 * Hidden files and `node_modules` / `target` are excluded from both counts.
 */
async countFolderFiles(path: string) : Promise<Result<FolderCounts, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_folder_files", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readFile(req: ReadFileRequest) : Promise<Result<ReadFileResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async assembleFolder(req: AssembleFolderRequest) : Promise<Result<AssembleFolderResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("assemble_folder", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addQueuedMessage(req: AddQueuedMessageRequest) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_queued_message", { req }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listQueuedMessages(conversationId: string) : Promise<Result<QueuedMessage[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_queued_messages", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateQueuedMessage(id: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_queued_message", { id, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteQueuedMessage(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_queued_message", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reorderQueuedMessages(conversationId: string, orderedIds: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reorder_queued_messages", { conversationId, orderedIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mergeQueuedMessages(ids: string[]) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_queued_messages", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pin a conversation.
 */
async pinConversation(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pin_conversation", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unpin a conversation.
 */
async unpinConversation(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unpin_conversation", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update the workspace assignment of a conversation.
 */
async updateConversationWorkspace(id: string, workspaceId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_conversation_workspace", { id, workspaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConversationMessagesHeadings(conversationId: string) : Promise<Result<HeadingItem[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conversation_messages_headings", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
agentEvent: AgentEvent,
mcpEvent: McpEvent,
skillEvent: SkillEvent,
workflowEvent: WorkflowEvent
}>({
agentEvent: "agent-event",
mcpEvent: "mcp-event",
skillEvent: "skill-event",
workflowEvent: "workflow-event"
})

/** user-defined constants **/



/** user-defined types **/

export type AchievementData = { id: string; unlocked_at: string }
export type ActivityEventRequest = { event_type: string; metadata: JsonValue }
export type AddMcpServerPayload = { name: string; transport: string; command: string | null; args: string[] | null; url: string | null; env: Partial<{ [key in string]: string }> | null }
export type AddQueuedMessageRequest = { conversation_id: string; content: string; context_items: ContextItem[] | null }
/**
 * Payload for the `"agent-event"` Tauri channel.
 */
export type AgentEvent = { type: "cancelled"; conversation_id: string } | { type: "started"; conversation_id: string } | { type: "token"; conversation_id: string; delta: string } | { type: "tool_call"; conversation_id: string; tool_call: AgentToolCall } | { type: "tool_result"; conversation_id: string; tool_call_id: string; result: string } | { type: "done"; conversation_id: string; input_tokens: number; output_tokens: number } | { type: "error"; conversation_id: string; message: string } | { type: "persisted"; conversation_id: string } | { type: "tool_approval_required"; conversation_id: string; tool_call_id: string; tool_name: string; arguments: JsonValue } | { type: "stream_update"; conversation_id: string; document: NodeDocument; new_toc_items: TocItem[]; new_artifact_specs: ArtifactSpec[] } | { type: "provider_not_ready"; conversation_id: string; reason: string; fix_action: string } | { type: "thinking_stream_update"; conversation_id: string; document: NodeDocument } | { type: "thinking_done"; conversation_id: string; document: NodeDocument }
export type AgentToolCall = { id: string; name: string; arguments: JsonValue }
export type AnalyticsData = { total_conversations: string; total_messages: string; messages_per_day: DailyCount[]; conversations_per_day: DailyCount[]; skills_used: SkillUsage[]; token_usage: TokenTotals }
/**
 * Whether a given provider has a stored key.
 */
export type ApiKeyStatus = { provider: string; has_key: boolean }
export type ArtifactData = { id: string; message_id: string; branch_id: string | null; type: string; name: string; content: string; language: string | null; logical_key: string | null; created_at: string }
export type ArtifactSpec = { id: string; language: string; raw_code: string; slot_index: number }
export type AssembleFolderRequest = { path: string; deep: boolean; max_bytes: string | null }
export type AssembleFolderResponse = { assembled_content: string; file_count: string }
export type AutoApproveConfigDto = { auto_approve_reads: boolean; auto_approve_writes: boolean; auto_approve_shell: boolean; auto_approve_http_requests: boolean; auto_approve_selects: boolean; auto_approve_mutations: boolean }
export type BookmarkData = { id: string; message_id: string; heading_anchor: string | null; label: string | null; created_at: string }
export type BranchInfo = { id: string; name: string | null; parent_message_id: string; created_at: string; message_count: string }
export type ConfigScope = "global" | "workspace"
export type ContextItem = { type: "skill"; name: string } | { type: "file"; path: string; name: string; size: string | null } | { type: "folder"; path: string; name: string; scope: FolderScope; file_count: string }
export type ConversationBootstrapData = { messages: MessageData[]; branches: BranchInfo[]; draft: [string, JsonValue[]] | null; queued: QueuedMessage[]; headings: HeadingItem[] }
/**
 * Lightweight summary used by the sidebar list.
 */
export type ConversationSummary = { id: string; title: string | null; profile_id: string; profile_name: string | null; profile_deleted: boolean; workspace_id: string | null; created_at: string; updated_at: string; message_count: string; folder_id: string | null; pinned: boolean }
export type CreateBookmarkRequest = { conversation_id: string; message_id: string; heading_anchor: string | null; label: string | null }
export type CreateBranchRequest = { conversation_id: string; parent_message_id: string; name: string | null }
export type DailyCount = { date: string; count: string }
export type DiffResult = { diff: string; has_changes: boolean }
export type ExportFormat = "markdown" | "json"
/**
 * A single file or directory entry returned by `list_directory_contents`.
 */
export type FileEntry = { name: string; path: string; is_dir: boolean; size: string | null }
/**
 * Shallow vs deep file counts for a folder, used by `FolderScopeModal`.
 */
export type FolderCounts = { shallow: string; deep: string }
export type FolderData = { id: string; name: string; created_at: string }
/**
 * Determines how deeply to traverse a folder when assembling content.
 * Stored as a string in the JSON column (e.g., "shallow" or "deep").
 */
export type FolderScope = "shallow" | "deep"
export type GistFile = { filename: string; content: string }
export type GistInfo = { id: string; url: string; html_url: string; description: string }
export type HeadingItem = { id: string; message_id: string; toc_index: number; text: string; level: number }
export type HydrateResponse = { local_id: string }
/**
 * Result returned after a successful installation.
 */
export type InstallResult = { skill_name: string; installed_path: string; target: InstallTarget }
/**
 * Target location for installing a skill.
 */
export type InstallTarget = 
/**
 * `~/.agents/skills/<name>/`
 */
"personal" | 
/**
 * `./.skilldeck/skills/<name>/` relative to cwd
 */
"workspace"
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * File location for a warning.
 */
export type LintLocation = { file: string; line: string | null; column: string | null }
/**
 * A single lint warning emitted by a rule.
 */
export type LintWarning = { rule_id: string; severity: Severity; message: string; location: LintLocation | null; 
/**
 * UX Addition: Allows the UI to suggest/auto-apply a fix.
 */
suggested_fix: string | null }
/**
 * Payload for the `"mcp-event"` Tauri channel.
 */
export type McpEvent = { type: "server_connected"; name: string } | { type: "server_disconnected"; name: string } | { type: "server_failed"; name: string; message: string } | { type: "tool_discovered"; server: string; tool: McpToolInfo }
export type McpServerResponse = { id: string; name: string; transport: string; status: string; tools: McpToolResponse[] }
export type McpToolInfo = { name: string; description: string }
export type McpToolResponse = { name: string; description: string; input_schema: JsonValue }
export type MdNode = { type: "paragraph"; id: string; html: string } | { type: "heading"; id: string; level: number; text: string; slug: string; toc_index: number } | { type: "code_block"; id: string; language: string; raw_code: string; highlighted_html: string; artifact_id: string } | { type: "list"; id: string; ordered: boolean; html: string } | { type: "blockquote"; id: string; html: string } | { type: "horizontal_rule"; id: string } | { type: "html_block"; id: string; html: string }
/**
 * Serialisable message returned to the frontend.
 */
export type MessageData = { id: string; conversation_id: string; role: string; content: string; created_at: string; compacted: boolean; context_items: ContextItem[] | null; metadata: MessageMetadata | null; input_tokens: number | null; output_tokens: number | null; seen: boolean; node_document: NodeDocument | null; status: string; thinking_content: string | null; thinking_document: NodeDocument | null }
/**
 * Lightweight message representation used by the Markdown gist exporter.
 */
export type MessageExport = { role: string; content: string }
/**
 * Typed metadata stored on every message row.
 */
export type MessageMetadata = { from_queue?: boolean | null; queued_at?: string | null; tool_name?: string | null; tool_call_id?: string | null }
export type NodeDocument = { stable_nodes: MdNode[]; draft_nodes: MdNode[]; toc_items: TocItem[]; artifact_specs: ArtifactSpec[] }
export type OllamaModelInfo = { id: string; name: string }
export type PendingNudge = { id: string; message: string; cta_label: string | null; cta_action: string | null; created_at: string }
export type PlatformPreferences = { email: string | null; email_verified: boolean; nudge_frequency: string; nudge_opt_out: boolean; notification_channels: string[]; theme_preference: string; timezone: string | null; analytics_opt_in: boolean }
export type ProfileData = { id: string; name: string; model_provider: string; model_id: string; is_default: boolean; system_prompt: string | null; deleted_at: string | null }
export type ProviderReadyInfo = { profile_id: string; status: ProviderReadyStatus }
export type ProviderReadyStatus = { status: "ready" } | { status: "not_ready"; reason: string; fix_action: string }
export type QueuedMessage = { id: string; conversation_id: string; content: string; position: number; created_at: string; updated_at: string }
export type ReadFileRequest = { path: string; max_bytes: string | null }
export type ReadFileResponse = { content: string; size: string }
export type ReferralCode = { id: string; code: string; uses: number; max_uses: number; created_at: string }
export type ReferralStats = { code: ReferralCode; total_signups: string; total_conversions: string; rewards_earned: string }
export type RegistrySkillData = { id: string; name: string; description: string; source: string; sourceUrl: string | null; version: string | null; author: string | null; license: string | null; tags: string[]; category: string | null; lintWarnings: JsonValue[]; securityScore: number; qualityScore: number; metadataSource: string; content: string; createdAt: string; updatedAt: string }
export type SaveWorkflowDefinitionRequest = { name: string; definition: JsonValue }
/**
 * Request for searching messages within a conversation.
 */
export type SearchMessagesRequest = { conversation_id: string; query: string; limit: string | null }
/**
 * Result of a search within a conversation.
 */
export type SearchMessagesResult = { message_id: string; snippet: string }
export type SendMessageRequest = { conversation_id: string; content: string; branch_id: string | null; context_items: ContextItem[] | null; thinking: boolean | null }
/**
 * Severity level of a lint warning.
 */
export type Severity = "off" | "info" | "warning" | "error"
export type ShareResponse = { share_token: string }
export type SharedConversationMessage = { id: string; role: string; content: string; created_at: string; branch_id: string | null }
export type SharedConversationPayload = { id: string; title: string; messages: SharedConversationMessage[]; created_at: string }
/**
 * Payload for the `"skill-event"` Tauri channel.
 */
export type SkillEvent = { type: "updated"; source_label: string; skill_name: string }
export type SkillInfo = { name: string; description: string; is_active: boolean; source: string; path: string | null; lint_warnings: LintWarning[]; security_score: number; quality_score: number }
export type SkillSourceInfo = { id: string; source_type: string; path: string; label: string | null }
export type SkillUsage = { name: string; count: string }
export type SyncConversationRequest = { title: string; messages: SharedConversationMessage[] }
export type SyncConversationResponse = { share_token: string }
export type SyncStatusResponse = { is_synced: boolean; last_synced_at: string | null }
export type ThemeInfo = { name: string; display_name: string }
export type TocItem = { id: string; toc_index: number; text: string; level: number; slug: string }
export type TokenTotals = { input_tokens: string; output_tokens: string; total_tokens: string }
export type UpdatePreferencesRequest = { email: string | null; nudge_frequency: string | null; nudge_opt_out: boolean | null; notification_channels: string[] | null; theme_preference: string | null; timezone: string | null; analytics_opt_in: boolean | null }
export type WorkflowDefinitionResponse = { id: string; name: string; definition: JsonValue; created_at: string; updated_at: string }
/**
 * Payload for the `"workflow-event"` Tauri channel.
 */
export type WorkflowEvent = { type: "started"; id: string } | { type: "step_started"; workflow_id: string; step_id: string } | { type: "step_completed"; workflow_id: string; step_id: string; result: string | null } | { type: "step_failed"; workflow_id: string; step_id: string; error: string } | { type: "completed"; id: string } | { type: "failed"; id: string; message: string }
export type WorkspaceData = { id: string; path: string; name: string; project_type: string; is_open: boolean; context_files: string[]; indexed_file_count: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
