allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  es5-ext: true
  esbuild: true
  lefthook: true
  msw: true
  sharp: true

overrides:
  js-yaml: 4.1.0

packages:
  - '.'
  - './e2e-tests'
  - "./skilldeck-user-docs"
  - "./skilldeck-landing"
  - "./skilldeck-marketing-assets"