// src-tauri/src/commands/mod.rs
//! Tauri command modules.
pub mod achievements;
pub mod analytics;
pub mod artifacts;
pub mod attachments;
pub mod bookmarks;
pub mod branches;
pub mod conversations;
pub mod drafts;
pub mod export;
pub mod files;
pub mod folders;
pub mod gist;
pub mod headings;
pub mod home_dir;
pub mod mcp;
pub mod messages;
pub mod ollama;
pub mod platform;
pub mod profiles;
pub mod provider_ready;
pub mod queue;
pub mod run_code;
pub mod settings;
pub mod skills;
pub mod theme;
pub mod workflows;
pub mod workspaces;
