// src/components/workspace/file-tree-panel.tsx
import { useQuery } from '@tanstack/react-query'
import { openUrl } from '@tauri-apps/plugin-opener'
import {
  Tree,
  File as TreeFile,
  Folder as TreeFolder,
  type TreeViewElement,
} from '@/components/ui/file-tree'
import { commands } from '@/lib/bindings'
import { useSettingsStore } from '@/store/settings'
import { useWorkspaceStore } from '@/store/workspace'
// Adjust this import path to where you saved the hook
import { useWorkspaces } from '@/hooks/use-workspaces'

// Define this locally, or export it from @/lib/bindings if it's generated by specta
interface FileEntry {
  name: string
  path: string
  is_dir: boolean
  children: FileEntry[]
}

export function FileTreePanel() {
  const { data: workspaces = [] } = useWorkspaces()
  const activeWorkspaceId = useWorkspaceStore((s) => s.activeWorkspaceId)
  const preferredEditor = useSettingsStore((s) => s.preferredEditor)

  const activeWorkspace = workspaces.find((w) => w.id === activeWorkspaceId)

  const handleFileClick = async (filePath: string) => {
    const schemes: Record<string, string> = {
      vscode: 'vscode://file/',
      cursor: 'cursor://file/',
    }
    const url = schemes[preferredEditor]
      ? `${schemes[preferredEditor]}${filePath}`
      : `file://${filePath}`

    await openUrl(url).catch(() => {
      openUrl(`file://${filePath}`)
    })
  }

  const { data: files, isLoading } = useQuery({
    queryKey: ['workspace-files', activeWorkspace?.path],
    queryFn: async () => {
      const res = await commands.listWorkspaceFiles(
        activeWorkspace!.path,
        4,
      )

      if (res.status === 'ok') return res.data
      throw new Error(res.error)
    },
    enabled: !!activeWorkspace?.path,
    staleTime: 30_000,
  })

  const transformFiles = (entries: FileEntry[]): TreeViewElement[] => {
    const sorted = entries.sort((a, b) => {
      if (a.is_dir !== b.is_dir) return a.is_dir ? -1 : 1
      return a.name.localeCompare(b.name)
    })

    return sorted.map((entry) => ({
      id: entry.path,
      name: entry.name,
      type: entry.is_dir ? ("folder" as const) : ("file" as const),
      children:
        entry.is_dir && entry.children?.length
          ? transformFiles(entry.children)
          : undefined,
    }))
  }

  // We map manually to `children` so we can inject the custom `onClick` for your editor opening logic
  const renderTree = (elements: TreeViewElement[]) => {
    return elements.map((element) => {
      if (element.type === "folder") {
        return (
          <TreeFolder key={element.id} value={element.id} element={element.name}>
            {element.children ? renderTree(element.children) : null}
          </TreeFolder>
        )
      }

      return (
        <TreeFile
          key={element.id}
          value={element.id}
          onClick={() => handleFileClick(element.id)}
          // Override the default "w-fit" so the button stays within the panel bounds
          className="w-full min-w-0"
        >
          {/* "truncate" applies: overflow-hidden, text-overflow: ellipsis, white-space: nowrap */}
          <span className="truncate">{element.name}</span>
        </TreeFile>
      )
    })
  }
  if (!activeWorkspace) {
    return (
      <div className="flex h-full items-center justify-center p-4 text-sm text-muted-foreground">
        No workspace open
      </div>
    )
  }

  if (isLoading) {
    return (
      <div className="flex h-full items-center justify-center p-4">
        <div className="h-4 w-4 animate-spin rounded-full border-2 border-primary border-t-transparent" />
      </div>
    )
  }

  const treeElements = files ? transformFiles(files) : []

  return (
    <Tree className="h-full" indicator>
      {treeElements.length > 0 ? (
        renderTree(treeElements)
      ) : (
        <div className="p-4 text-center text-sm text-muted-foreground">
          No files found in workspace
        </div>
      )}
    </Tree>
  )
}
