// src/components/skills/skill-card.tsx
// Skill card for the browser grid — shows trust badge, AI tag indicator, and lint summary.
// Ensures one card per line with no horizontal overflow.

import { Bot, ExternalLink, Package, Tag, User } from 'lucide-react'
import { useState } from 'react'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle
} from '@/components/ui/alert-dialog'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { useUninstallSkill } from '@/hooks/use-skills'
import type { RegistrySkillData, SkillInfo } from '@/lib/bindings'
import { cn } from '@/lib/utils'
import { TrustBadge } from './trust-badge'

interface SkillCardProps {
  skill: RegistrySkillData | (SkillInfo & { _sourceType: 'local' })
  isInstalled?: boolean
  onSelect?: () => void
  onInstall?: () => void
  className?: string
}

export function SkillCard({
  skill,
  isInstalled = false,
  onSelect,
  onInstall,
  className
}: SkillCardProps) {
  const [showRemoveConfirm, setShowRemoveConfirm] = useState(false)
  const uninstallSkill = useUninstallSkill()

  const isLocal = '_sourceType' in skill && skill._sourceType === 'local'
  const isRegistry = !isLocal

  const registrySkill = isRegistry
    ? (skill as unknown as RegistrySkillData)
    : null
  const localSkill = isLocal
    ? (skill as SkillInfo & { _sourceType: 'local' })
    : null

  const errorCount = registrySkill
    ? registrySkill.lintWarnings.filter((w: any) => w.severity === 'error')
        .length
    : 0
  const isAiTagged = registrySkill?.metadataSource === 'llm_enrichment'
  const tags = registrySkill?.tags ?? []

  const handleRemove = (e: React.MouseEvent) => {
    e.stopPropagation()
    setShowRemoveConfirm(true)
  }

  return (
    <>
      <div
        role={onSelect ? 'button' : undefined}
        tabIndex={onSelect ? 0 : undefined}
        onClick={onSelect}
        onKeyDown={(e) => e.key === 'Enter' && onSelect?.()}
        className={cn(
          'group flex flex-col gap-3 rounded-lg border border-border bg-card p-4 text-sm transition-all w-full min-w-0 overflow-hidden',
          onSelect && 'cursor-pointer hover:border-primary/50 hover:shadow-sm',
          className
        )}
      >
        {/* Header row */}
        <div className="flex items-start gap-3 min-w-0">
          <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-muted text-muted-foreground">
            <Package className="size-4" />
          </div>
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="font-semibold truncate max-w-full">
                {skill.name}
              </span>
              {registrySkill?.version && (
                <span className="text-[10px] text-muted-foreground font-mono shrink-0">
                  v{registrySkill.version}
                </span>
              )}
            </div>
            <p className="text-xs text-muted-foreground line-clamp-2 mt-0.5 break-words overflow-hidden">
              {skill.description}
            </p>
          </div>
        </div>

        {/* Trust badge + source badge */}
        <div className="flex items-center gap-2 flex-wrap min-w-0">
          {isRegistry && registrySkill ? (
            <TrustBadge
              securityScore={registrySkill.securityScore}
              qualityScore={registrySkill.qualityScore}
            />
          ) : (
            <Badge
              variant="secondary"
              className="inline-flex items-center gap-1"
            >
              <Tag className="size-2.5" />
              Local
            </Badge>
          )}
          {isInstalled && (
            <Badge
              variant="default"
              className="bg-primary/10 text-primary border-primary/20"
            >
              Installed
            </Badge>
          )}
        </div>

        {/* Tags */}
        {tags.length > 0 && (
          <div className="flex items-center gap-1 flex-wrap min-w-0">
            {isAiTagged && (
              <span
                className="inline-flex items-center gap-0.5 text-[10px] text-muted-foreground shrink-0"
                title="Tags generated by AI enrichment"
              >
                <Bot className="size-2.5" />
                AI
              </span>
            )}
            {tags.slice(0, 3).map((tag: string) => (
              <Badge
                key={tag}
                variant="secondary"
                className="h-5 px-1.5 text-[10px] font-normal max-w-full truncate"
              >
                {tag}
              </Badge>
            ))}
            {tags.length > 3 && (
              <span className="text-[10px] text-muted-foreground shrink-0">
                +{tags.length - 3}
              </span>
            )}
          </div>
        )}

        {/* Footer row */}
        <div className="flex items-center justify-between gap-2 mt-auto pt-1 border-t border-border/50 min-w-0">
          <div className="flex items-center gap-3 text-[11px] text-muted-foreground min-w-0 flex-wrap">
            {registrySkill?.author && (
              <span className="flex items-center gap-1 truncate max-w-full">
                <User className="size-3 shrink-0" />
                <span className="truncate">{registrySkill.author}</span>
              </span>
            )}
            {/* Removed redundant "Source: local" line */}
            {errorCount > 0 && (
              <span className="text-destructive shrink-0">
                {errorCount} issue{errorCount > 1 ? 's' : ''}
              </span>
            )}
          </div>

          <div className="flex items-center gap-1 shrink-0">
            {isLocal && (
              <Button size="sm" variant="destructive" onClick={handleRemove}>
                Remove
              </Button>
            )}
            {isRegistry && !isInstalled && onInstall && (
              <Button
                size="sm"
                onClick={(e) => {
                  e.stopPropagation()
                  onInstall()
                }}
              >
                Install
              </Button>
            )}
            {registrySkill?.sourceUrl && (
              <Button
                size="icon-xs"
                variant="ghost"
                asChild
                onClick={(e) => e.stopPropagation()}
                title="View source"
              >
                <a
                  href={registrySkill.sourceUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <ExternalLink className="size-3" />
                </a>
              </Button>
            )}
          </div>
        </div>
      </div>

      {/* Remove confirmation dialog */}
      {showRemoveConfirm && localSkill && (
        <AlertDialog open onOpenChange={setShowRemoveConfirm}>
          <AlertDialogContent>
            <AlertDialogHeader>
              <AlertDialogTitle>Remove local skill</AlertDialogTitle>
              <AlertDialogDescription>
                This will permanently delete the skill folder from your disk:
                <code className="block mt-2 p-2 bg-muted rounded text-xs break-all">
                  {localSkill.path || localSkill.name}
                </code>
                This action cannot be undone.
              </AlertDialogDescription>
            </AlertDialogHeader>
            <AlertDialogFooter>
              <AlertDialogCancel>Cancel</AlertDialogCancel>
              <AlertDialogAction
                onClick={() => {
                  uninstallSkill.mutate({
                    skillName: skill.name,
                    target: 'personal'
                  })
                  setShowRemoveConfirm(false)
                }}
              >
                Delete permanently
              </AlertDialogAction>
            </AlertDialogFooter>
          </AlertDialogContent>
        </AlertDialog>
      )}
    </>
  )
}
