// src/components/skills/skill-card.tsx
// Skill card for the browser grid — shows trust badge, AI tag indicator, and lint summary.

import {
  Bot,
  ExternalLink,
  Package,
  Tag,
  User
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { TrustBadge } from './trust-badge'
import type { RegistrySkill } from '@/lib/invoke'

interface SkillCardProps {
  skill: RegistrySkill
  isInstalled?: boolean
  onSelect?: () => void
  onInstall?: () => void
  className?: string
}

export function SkillCard({
  skill,
  isInstalled = false,
  onSelect,
  onInstall,
  className
}: SkillCardProps) {
  const errorCount = skill.lintWarnings.filter(
    (w) => w.severity === 'error'
  ).length
  const isAiTagged = skill.metadataSource === 'llm_enrichment'

  return (
    <div
      role={onSelect ? 'button' : undefined}
      tabIndex={onSelect ? 0 : undefined}
      onClick={onSelect}
      onKeyDown={(e) => e.key === 'Enter' && onSelect?.()}
      className={cn(
        'group flex flex-col gap-3 rounded-lg border border-border bg-card p-4 text-sm transition-all',
        onSelect && 'cursor-pointer hover:border-primary/50 hover:shadow-sm',
        className
      )}
    >
      {/* Header row */}
      <div className="flex items-start gap-3">
        <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-muted text-muted-foreground">
          <Package className="size-4" />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-semibold truncate">{skill.name}</span>
            {skill.version && (
              <span className="text-[10px] text-muted-foreground font-mono">
                v{skill.version}
              </span>
            )}
          </div>
          <p className="text-xs text-muted-foreground line-clamp-2 mt-0.5">
            {skill.description}
          </p>
        </div>
      </div>

      {/* Trust badge + source badge */}
      <div className="flex items-center gap-2 flex-wrap">
        <TrustBadge
          securityScore={skill.securityScore}
          qualityScore={skill.qualityScore}
        />
        {isInstalled && (
          <span className="inline-flex items-center gap-1 rounded-full bg-primary/10 px-2 py-0.5 text-[11px] font-medium text-primary">
            Installed
          </span>
        )}
        <SourceBadge source={skill.source} />
      </div>

      {/* Tags */}
      {skill.tags.length > 0 && (
        <div className="flex items-center gap-1 flex-wrap">
          {isAiTagged && (
            <span
              className="inline-flex items-center gap-0.5 text-[10px] text-muted-foreground"
              title="Tags generated by AI enrichment"
            >
              <Bot className="size-2.5" />
              AI
            </span>
          )}
          {skill.tags.slice(0, 5).map((tag) => (
            <Badge
              key={tag}
              variant="secondary"
              className="h-5 px-1.5 text-[10px] font-normal"
            >
              {tag}
            </Badge>
          ))}
          {skill.tags.length > 5 && (
            <span className="text-[10px] text-muted-foreground">
              +{skill.tags.length - 5}
            </span>
          )}
        </div>
      )}

      {/* Footer row */}
      <div className="flex items-center justify-between gap-2 mt-auto pt-1 border-t border-border/50">
        <div className="flex items-center gap-3 text-[11px] text-muted-foreground">
          {skill.author && (
            <span className="flex items-center gap-1">
              <User className="size-3" />
              {skill.author}
            </span>
          )}
          {errorCount > 0 && (
            <span className="text-destructive">
              {errorCount} issue{errorCount > 1 ? 's' : ''}
            </span>
          )}
        </div>

        {!isInstalled && onInstall && (
          <Button
            size="sm"
            className="h-7 text-xs"
            onClick={(e) => {
              e.stopPropagation()
              onInstall()
            }}
          >
            Install
          </Button>
        )}
        {skill.sourceUrl && (
          <a
            href={skill.sourceUrl}
            target="_blank"
            rel="noopener noreferrer"
            onClick={(e) => e.stopPropagation()}
            className="text-muted-foreground hover:text-foreground transition-colors"
            title="View source"
          >
            <ExternalLink className="size-3" />
          </a>
        )}
      </div>
    </div>
  )
}

function SourceBadge({ source }: { source: string }) {
  return (
    <span className="inline-flex items-center gap-1 rounded-full bg-muted px-2 py-0.5 text-[11px] font-medium text-muted-foreground">
      <Tag className="size-2.5" />
      {source}
    </span>
  )
}
