import type { Metadata } from 'next'
import { PageLayout } from '@/components/shared/PageLayout'

export const metadata: Metadata = {
  title: 'Terms of Use',
  description: 'SkillDeck terms of use. Open source software under MIT License.',
}

export default function TermsPage() {
  return (
    <PageLayout>
      <div className="py-16 sm:py-24">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="text-4xl font-bold tracking-tight mb-4">Terms of Use</h1>
          <p className="text-sm text-muted-foreground mb-12">Last updated: January 15, 2025</p>

          <div className="prose prose-invert prose-slate max-w-none space-y-8 text-muted-foreground leading-relaxed">
            <section>
              <h2 className="text-xl font-semibold text-foreground mb-3">License</h2>
              <p>
                SkillDeck is distributed under the MIT License. You are free to use, copy, modify,
                merge, publish, distribute, sublicense, and/or sell copies of the software, subject to the
                conditions of the license.
              </p>
              <p className="mt-3">
                The full text of the license is available in the source code repository.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-foreground mb-3">No Warranty</h2>
              <p>
                SkillDeck is provided &quot;as is&quot; without warranty of any kind, express or implied,
                including but not limited to the warranties of merchantability, fitness for a particular
                purpose, and noninfringement. In no event shall the authors or copyright holders be liable
                for any claim, damages, or other liability arising from the use of the software.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-foreground mb-3">User Responsibilities</h2>
              <p>
                You are responsible for your use of SkillDeck, including any interactions with AI models,
                external tools connected through MCP, and the output generated by your agent workflows.
                SkillDeck does not control the behavior of third-party LLM providers or MCP servers.
              </p>
              <p className="mt-3">
                You are responsible for ensuring that your use of AI models complies with the terms of
                service of your chosen model providers (OpenAI, Anthropic, etc.).
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-foreground mb-3">API Key Management</h2>
              <p>
                SkillDeck stores your API keys in your operating system&apos;s native keychain. You are
                responsible for the security of your API keys and should not share them. SkillDeck
                transmits API keys only to the intended API endpoints and does not log or expose them.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-foreground mb-3">Community Content</h2>
              <p>
                Skills, MCP servers, and other community-contributed content available through the Skill
                Marketplace are provided by their respective authors. SkillDeck does not review, endorse,
                or take responsibility for third-party content. The Skill Linter provides automated
                security and quality checks, but these do not guarantee the safety or correctness of
                community content.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-foreground mb-3">Optional Platform Services</h2>
              <p>
                The optional SkillDeck Platform may have additional terms for cloud-based features such as
                skill registry access, user accounts, and analytics. Use of the platform is entirely
                optional, and the desktop application functions fully without it.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-foreground mb-3">Changes</h2>
              <p>
                We may update these terms from time to time. Changes will be documented in the source code
                repository. Continued use of SkillDeck after changes constitutes acceptance of the updated
                terms.
              </p>
            </section>
          </div>
        </div>
      </div>
    </PageLayout>
  )
}
