// src/components/conversation/artifact-card.tsx
/**
 * ArtifactCard — displays a code or text artifact generated by the agent.
 * Supports copy-to-clipboard and (future) save-to-file.
 */

import { useState } from 'react'
import { Check, Copy, FileCode, FileText } from 'lucide-react'

type ArtifactType = 'code' | 'text' | 'markdown'

interface ArtifactCardProps {
  title: string
  type: ArtifactType
  language?: string
  content: string
}

export function ArtifactCard({
  title,
  type,
  language,
  content
}: ArtifactCardProps) {
  const [copied, setCopied] = useState(false)

  const copy = async () => {
    await navigator.clipboard.writeText(content)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const Icon = type === 'code' ? FileCode : FileText
  const label = type === 'code' ? (language ?? 'code') : type

  return (
    <div className="my-2 rounded-lg border border-border overflow-hidden text-sm">
      {/* Header */}
      <div className="flex items-center gap-2 bg-muted/70 px-3 py-2 border-b border-border">
        <Icon className="size-3.5 text-muted-foreground shrink-0" />
        <span className="font-medium flex-1 truncate text-xs">{title}</span>
        <span className="text-[10px] text-muted-foreground font-mono">
          {label}
        </span>
        <button
          type="button"
          onClick={copy}
          className="ml-1 p-1 rounded hover:bg-muted transition-colors text-muted-foreground hover:text-foreground"
          aria-label="Copy artifact"
        >
          {copied ? (
            <Check className="size-3.5 text-green-500" />
          ) : (
            <Copy className="size-3.5" />
          )}
        </button>
      </div>

      {/* Content */}
      <pre className="px-3 py-2.5 overflow-x-auto text-xs font-mono leading-relaxed whitespace-pre bg-background">
        {content}
      </pre>
    </div>
  )
}
