/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings.index'
import { Route as AppSharedShareTokenRouteImport } from './routes/_app/shared.$shareToken'
import { Route as AppSettingsSourcesRouteImport } from './routes/_app/settings.sources'
import { Route as AppSettingsShortcutsRouteImport } from './routes/_app/settings.shortcuts'
import { Route as AppSettingsReferralRouteImport } from './routes/_app/settings.referral'
import { Route as AppSettingsProfilesRouteImport } from './routes/_app/settings.profiles'
import { Route as AppSettingsPreferencesRouteImport } from './routes/_app/settings.preferences'
import { Route as AppSettingsPlatformRouteImport } from './routes/_app/settings.platform'
import { Route as AppSettingsLintRouteImport } from './routes/_app/settings.lint'
import { Route as AppSettingsApprovalsRouteImport } from './routes/_app/settings.approvals'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app/settings.appearance'
import { Route as AppSettingsApiKeysRouteImport } from './routes/_app/settings.api-keys'
import { Route as AppSettingsAchievementsRouteImport } from './routes/_app/settings.achievements'
import { Route as AppConversationsConversationIdRouteImport } from './routes/_app/conversations.$conversationId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute
} as any)
const AppSharedShareTokenRoute = AppSharedShareTokenRouteImport.update({
  id: '/shared/$shareToken',
  path: '/shared/$shareToken',
  getParentRoute: () => AppRoute
} as any)
const AppSettingsSourcesRoute = AppSettingsSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppSettingsRoute
} as any)
const AppSettingsShortcutsRoute = AppSettingsShortcutsRouteImport.update({
  id: '/shortcuts',
  path: '/shortcuts',
  getParentRoute: () => AppSettingsRoute
} as any)
const AppSettingsReferralRoute = AppSettingsReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AppSettingsRoute
} as any)
const AppSettingsProfilesRoute = AppSettingsProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AppSettingsRoute
} as any)
const AppSettingsPreferencesRoute = AppSettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AppSettingsRoute
} as any)
const AppSettingsPlatformRoute = AppSettingsPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AppSettingsRoute
} as any)
const AppSettingsLintRoute = AppSettingsLintRouteImport.update({
  id: '/lint',
  path: '/lint',
  getParentRoute: () => AppSettingsRoute
} as any)
const AppSettingsApprovalsRoute = AppSettingsApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppSettingsRoute
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRoute
} as any)
const AppSettingsApiKeysRoute = AppSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppSettingsRoute
} as any)
const AppSettingsAchievementsRoute = AppSettingsAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppSettingsRoute
} as any)
const AppConversationsConversationIdRoute =
  AppConversationsConversationIdRouteImport.update({
    id: '/conversations/$conversationId',
    path: '/conversations/$conversationId',
    getParentRoute: () => AppRoute
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/conversations/$conversationId': typeof AppConversationsConversationIdRoute
  '/settings/achievements': typeof AppSettingsAchievementsRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/approvals': typeof AppSettingsApprovalsRoute
  '/settings/lint': typeof AppSettingsLintRoute
  '/settings/platform': typeof AppSettingsPlatformRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/settings/profiles': typeof AppSettingsProfilesRoute
  '/settings/referral': typeof AppSettingsReferralRoute
  '/settings/shortcuts': typeof AppSettingsShortcutsRoute
  '/settings/sources': typeof AppSettingsSourcesRoute
  '/shared/$shareToken': typeof AppSharedShareTokenRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/conversations/$conversationId': typeof AppConversationsConversationIdRoute
  '/settings/achievements': typeof AppSettingsAchievementsRoute
  '/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/approvals': typeof AppSettingsApprovalsRoute
  '/settings/lint': typeof AppSettingsLintRoute
  '/settings/platform': typeof AppSettingsPlatformRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/settings/profiles': typeof AppSettingsProfilesRoute
  '/settings/referral': typeof AppSettingsReferralRoute
  '/settings/shortcuts': typeof AppSettingsShortcutsRoute
  '/settings/sources': typeof AppSettingsSourcesRoute
  '/shared/$shareToken': typeof AppSharedShareTokenRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/conversations/$conversationId': typeof AppConversationsConversationIdRoute
  '/_app/settings/achievements': typeof AppSettingsAchievementsRoute
  '/_app/settings/api-keys': typeof AppSettingsApiKeysRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/approvals': typeof AppSettingsApprovalsRoute
  '/_app/settings/lint': typeof AppSettingsLintRoute
  '/_app/settings/platform': typeof AppSettingsPlatformRoute
  '/_app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/_app/settings/profiles': typeof AppSettingsProfilesRoute
  '/_app/settings/referral': typeof AppSettingsReferralRoute
  '/_app/settings/shortcuts': typeof AppSettingsShortcutsRoute
  '/_app/settings/sources': typeof AppSettingsSourcesRoute
  '/_app/shared/$shareToken': typeof AppSharedShareTokenRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/conversations/$conversationId'
    | '/settings/achievements'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/approvals'
    | '/settings/lint'
    | '/settings/platform'
    | '/settings/preferences'
    | '/settings/profiles'
    | '/settings/referral'
    | '/settings/shortcuts'
    | '/settings/sources'
    | '/shared/$shareToken'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conversations/$conversationId'
    | '/settings/achievements'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/approvals'
    | '/settings/lint'
    | '/settings/platform'
    | '/settings/preferences'
    | '/settings/profiles'
    | '/settings/referral'
    | '/settings/shortcuts'
    | '/settings/sources'
    | '/shared/$shareToken'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/_app/settings'
    | '/_app/'
    | '/_app/conversations/$conversationId'
    | '/_app/settings/achievements'
    | '/_app/settings/api-keys'
    | '/_app/settings/appearance'
    | '/_app/settings/approvals'
    | '/_app/settings/lint'
    | '/_app/settings/platform'
    | '/_app/settings/preferences'
    | '/_app/settings/profiles'
    | '/_app/settings/referral'
    | '/_app/settings/shortcuts'
    | '/_app/settings/sources'
    | '/_app/shared/$shareToken'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/shared/$shareToken': {
      id: '/_app/shared/$shareToken'
      path: '/shared/$shareToken'
      fullPath: '/shared/$shareToken'
      preLoaderRoute: typeof AppSharedShareTokenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/sources': {
      id: '/_app/settings/sources'
      path: '/sources'
      fullPath: '/settings/sources'
      preLoaderRoute: typeof AppSettingsSourcesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/shortcuts': {
      id: '/_app/settings/shortcuts'
      path: '/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof AppSettingsShortcutsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/referral': {
      id: '/_app/settings/referral'
      path: '/referral'
      fullPath: '/settings/referral'
      preLoaderRoute: typeof AppSettingsReferralRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/profiles': {
      id: '/_app/settings/profiles'
      path: '/profiles'
      fullPath: '/settings/profiles'
      preLoaderRoute: typeof AppSettingsProfilesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/preferences': {
      id: '/_app/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AppSettingsPreferencesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/platform': {
      id: '/_app/settings/platform'
      path: '/platform'
      fullPath: '/settings/platform'
      preLoaderRoute: typeof AppSettingsPlatformRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/lint': {
      id: '/_app/settings/lint'
      path: '/lint'
      fullPath: '/settings/lint'
      preLoaderRoute: typeof AppSettingsLintRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/approvals': {
      id: '/_app/settings/approvals'
      path: '/approvals'
      fullPath: '/settings/approvals'
      preLoaderRoute: typeof AppSettingsApprovalsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/api-keys': {
      id: '/_app/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AppSettingsApiKeysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/achievements': {
      id: '/_app/settings/achievements'
      path: '/achievements'
      fullPath: '/settings/achievements'
      preLoaderRoute: typeof AppSettingsAchievementsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/conversations/$conversationId': {
      id: '/_app/conversations/$conversationId'
      path: '/conversations/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof AppConversationsConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAchievementsRoute: typeof AppSettingsAchievementsRoute
  AppSettingsApiKeysRoute: typeof AppSettingsApiKeysRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsApprovalsRoute: typeof AppSettingsApprovalsRoute
  AppSettingsLintRoute: typeof AppSettingsLintRoute
  AppSettingsPlatformRoute: typeof AppSettingsPlatformRoute
  AppSettingsPreferencesRoute: typeof AppSettingsPreferencesRoute
  AppSettingsProfilesRoute: typeof AppSettingsProfilesRoute
  AppSettingsReferralRoute: typeof AppSettingsReferralRoute
  AppSettingsShortcutsRoute: typeof AppSettingsShortcutsRoute
  AppSettingsSourcesRoute: typeof AppSettingsSourcesRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAchievementsRoute: AppSettingsAchievementsRoute,
  AppSettingsApiKeysRoute: AppSettingsApiKeysRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsApprovalsRoute: AppSettingsApprovalsRoute,
  AppSettingsLintRoute: AppSettingsLintRoute,
  AppSettingsPlatformRoute: AppSettingsPlatformRoute,
  AppSettingsPreferencesRoute: AppSettingsPreferencesRoute,
  AppSettingsProfilesRoute: AppSettingsProfilesRoute,
  AppSettingsReferralRoute: AppSettingsReferralRoute,
  AppSettingsShortcutsRoute: AppSettingsShortcutsRoute,
  AppSettingsSourcesRoute: AppSettingsSourcesRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren
)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppConversationsConversationIdRoute: typeof AppConversationsConversationIdRoute
  AppSharedShareTokenRoute: typeof AppSharedShareTokenRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppConversationsConversationIdRoute: AppConversationsConversationIdRoute,
  AppSharedShareTokenRoute: AppSharedShareTokenRoute
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
