// src/components/ui/provider-icon.tsx
import {
  Alibaba,
  AlibabaCloud,
  Anthropic,
  Aws,
  Azure,
  Baichuan,
  Baidu,
  BaiduCloud,
  Bedrock,
  ByteDance,
  Cerebras,
  Civitai,
  Cloudflare,
  Cohere,
  ComfyUI,
  Coze,
  DeepInfra,
  DeepSeek,
  Dify,
  Doubao,
  Fireworks,
  Github,
  Google,
  GoogleCloud,
  Groq,
  Huawei,
  HuggingFace,
  Hunyuan,
  IFlyTekCloud,
  LeptonAI,
  LobeHub,
  Meta,
  Microsoft,
  Midjourney,
  Minimax,
  Mistral,
  ModelScope,
  Moonshot,
  Novita,
  Nvidia,
  Ollama,
  OpenAI,
  OpenRouter,
  Perplexity,
  Qwen,
  Replicate,
  SambaNova,
  SenseNova,
  SiliconCloud,
  Skywork,
  Spark,
  Stability,
  Stepfun,
  Tencent,
  TencentCloud,
  Together,
  Upstage,
  Vercel,
  VertexAI,
  Volcengine,
  Wenxin,
  XAI,
  Yi,
  Zhipu
} from '@lobehub/icons'

interface ProviderIconProps {
  provider: string
  size?: number
  className?: string
  colored?: boolean
}

// Strict exact-match map for Providers
const providerMap: Record<string, React.ComponentType<any>> = {
  openai: OpenAI,
  anthropic: Anthropic,
  google: Google,
  deepseek: DeepSeek,
  mistral: Mistral,
  cohere: Cohere,
  perplexity: Perplexity,
  ollama: Ollama,
  qwen: Qwen,
  zhipu: Zhipu,
  baidu: Baidu,
  tencent: Tencent,
  alibaba: Alibaba,
  alibabacloud: AlibabaCloud,
  alicloud: AlibabaCloud,
  baiducloud: BaiduCloud,
  tencentcloud: TencentCloud,
  volcengine: Volcengine,
  groq: Groq,
  meta: Meta,
  together: Together,
  'together.ai': Together,
  fireworks: Fireworks,
  aws: Aws,
  azure: Azure,
  azureai: Azure,
  bedrock: Bedrock,
  huggingface: HuggingFace,
  civitai: Civitai,
  stability: Stability,
  cloudflare: Cloudflare,
  vercel: Vercel,
  xai: XAI,
  moonshot: Moonshot,
  doubao: Doubao,
  yi: Yi,
  minimax: Minimax,
  stepfun: Stepfun,
  spark: Spark,
  wenxin: Wenxin,
  baichuan: Baichuan,
  hunyuan: Hunyuan,
  siliconcloud: SiliconCloud,
  siliconflow: SiliconCloud,
  novita: Novita,
  replicate: Replicate,
  sambanova: SambaNova,
  cerebras: Cerebras,
  deepinfra: DeepInfra,
  lepton: LeptonAI,
  leptonai: LeptonAI,
  github: Github,
  lobehub: LobeHub,
  bytedance: ByteDance,
  iflytek: IFlyTekCloud,
  sensetime: SenseNova,
  skywork: Skywork,
  nvidia: Nvidia,
  microsoft: Microsoft,
  huawei: Huawei,
  vertexai: VertexAI,
  googlecloud: GoogleCloud,
  dify: Dify,
  coze: Coze,
  midjourney: Midjourney,
  comfyui: ComfyUI,
  openrouter: OpenRouter,
  upstage: Upstage,
  modelscope: ModelScope
}

export function ProviderIcon({
  provider,
  size = 16,
  className,
  colored = true
}: ProviderIconProps) {
  if (!provider) return null
  const Icon = providerMap[provider.toLowerCase()]
  if (!Icon) return null // No fallback guess. If it's not in the map, render nothing.

  return (
    <Icon
      size={size}
      className={className}
      type={colored ? 'color' : undefined}
    />
  )
}
